title: Knowledge
theme: just-the-docs
description:  Documentation of technical notes, pointers and hacks.
baseurl: "/knowledge"
url: "https://akashp1712.github.io"
permalink: pretty
color_scheme: nil
search_enabled: true
search_tokenizer_separator: /[\s/]+/
aux_links:
  "See this on GitHub":
    - "//github.com/akashp1712/knowledge"
ga_tracking: 
footer_content: "Copyright &copy; 2022 Akash Panchal. Distributed by an <a href=\"https://github.com/akashp1712/knowledge/blob/master/LICENSE\">MIT license.</a>"
